<?php

$products = $this->getConfigurableProducts();

$helper = Mage::helper('demo');
?>

<h1>Misco Producs</h1>

<?php if (count($products) > 0) : ?>
    <ul>
        <?php foreach ($products as $product) : ?>
            <li>
                <a href="<?php echo $product->getProductURL(); ?>"><?php echo $product->getName();?></a>
                <span><?php echo $helper->beautifyPrice($product->getPrice());?> </span>
            </li>
        <?php endforeach; ?>
    </ul>
<?php else : ?>
    <p>Sorry, no products :( </p>
<?php endif; ?>