<?php

?>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>

<script>
    var map;
    function initialize() {



        var mapOptions = {
            zoom: 8,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
        var infowindow = new google.maps.InfoWindow();
        var bounds = new google.maps.LatLngBounds();

        <?php $i=0; foreach ($this->getStockists() as $stockist) : ?>
            var marker = new google.maps.Marker({
                position: new google.maps.LatLng(<?php echo $stockist->getLatitude().','.$stockist->getLongitude() ?>),
                map: map
            });
            bounds.extend(marker.position);

            google.maps.event.addListener(marker, 'click', (function (marker, i) {
                return function () {
                    infowindow.setContent('<?php echo 'Stockist # '.$stockist->getIncrementId() ?>');
                    infowindow.open(map, marker);
                }
            })(marker, <?php echo $i ?>));

        <?php $i++; endforeach; ?>

        map.fitBounds(bounds);

        var listener = google.maps.event.addListener(map, "idle", function () {
            map.setZoom(3);
            google.maps.event.removeListener(listener);
        });

    }

    google.maps.event.addDomListener(window, 'load', initialize);

</script>
<style>
    html, body, #map-canvas {
        height: 500px;
        margin: 10px;
        padding: 10px
    }
</style>

<h2><?php echo $this->getTitle(); ?></h2>

<div id="map-canvas">
</div>

