<?php

?>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>

<script>
    var map;
    function initialize() {
        var mapOptions = {
            zoom: 8,
            center: new google.maps.LatLng(-34.397, 150.644)
        };
        map = new google.maps.Map(document.getElementById('map-canvas'),
            mapOptions);
    }

    google.maps.event.addDomListener(window, 'load', initialize);

</script>
<style>
    html, body, #map-canvas {
        height: 500px;
        margin: 10px;
        padding: 10px
    }
</style>

<h2><?php echo $this->getTitle(); ?></h2>

<div id="map-canvas"></div>
